### PR TITLE
fix: order tree directory entries correctly (fixes #44)

### LINKED ISSUE #44: Wrong entry ordering in tree serialization
Hi everyone,

I'm working on [pando](https://github.com/pandonetwork/pando/) - a decentralized `git-remote` based on IPFS, Ethereum and Aragon - and I think I've spotted an error in how this resolver handles `tree` serialization.

If you have let's say a git repo with both a `test.md`and a `test` folder as in this repo [example](https://github.com/osarrouy/js-git-ipld-bug) git orders them this way:

```
git cat-file -p 66fdaafa5fac5abca298f9822bd2071d0dc258d2
100644 blob 557db03de997c86a4a028e1ebd3a1ceb225be238    test.md
040000 tree d564d0bc3dd917926892c55e3706cc116d5b165e    test
```

Now `js-ipld-git` is gonna order them the other way around:
```
{"test":{"hash":{"/":"z8mWaJC5XCFN365khYYEdFVkdHVnMMJ37"},"mode":"40000"},
"test.md":{"hash":{"/":"z8mWaGQjCphPSZpWxcC2gH3KeoCXCp1HH"},"mode":"100644"}}
```

This leads to an error where the result of the `shaToCid` function and the CID of the actually serialized `tree` object are not the same - thus breaking the whole commit tree.

This comes from the sorting function implemented [here](https://github.com/ipld/js-ipld-git/blob/master/src/util/tree.js#L14).

Do you think you guys could have a look or do you prefer me to dive deeper in it and open a PR?

### PR DESCRIPTION
**Pull request by sameer**
Added a trailing / when entries are directories for sorting.
Two test entries are added similar to those in #44 to confirm the fix.

### CODE REVIEW

**Review by vmx — APPROVED** [review]
LGTM, but could you @magik6k please have a look, you know more about Git than me :)

File: src/util/tree.js [hunk 1]
```diff
@@ -11,7 +11,11 @@ exports.serialize = (dagNode, callback) => {
   Object.keys(dagNode).forEach((name) => {
     entries.push([name, dagNode[name]])
   })
-  entries.sort((a, b) => a[0] > b[0] ? 1 : -1)
+  entries.sort((a, b) => {
+    const aName = a[0] + (a[1].mode === '40000' ? '/' : '')
+    const bName = b[0] + (b[1].mode === '40000' ? '/' : '')
```
Comment (magik6k) [inline src/util/tree.js:16]: I'm not 100% certain if `40000` is the only mode directories can have, but let's call it good enough

**Review by magik6k — APPROVED** [review]

File: src/util/tree.js (hunk 1 above)
Comment (sameer) [reply src/util/tree.js:16]: > I'm not 100% certain if `40000` is the only mode directories can have, but let's call it good enough

Found the [list of supported modes](https://github.com/git/git/blob/ecbdaf0899161c067986e9d9d564586d4b045d62/Documentation/git-fast-import.txt#L555), which specifies 040000 as the only mode for subdirectories.
